version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - ../Configs/.env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: inkululeko_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
