openapi: 3.0.0
info:
  title: Inkululeko API
  version: 1.0.0
  description: AI-assisted farming tools and mentorship platform

paths:
  /api/matchmaking:
    post:
      summary: Match farmers with buyers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FarmerInput'
      responses:
        '200':
          description: List of buyer matches

  /api/price-prediction:
    post:
      summary: Predict crop price
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PriceInput'
      responses:
        '200':
          description: Predicted price and market insight

  /api/mentor-pairing:
    post:
      summary: Recommend mentors for farmer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MenteeInput'
      responses:
        '200':
          description: Mentor recommendations

components:
  schemas:
    FarmerInput:
      type: object
      properties:
        location: { type: string }
        produce_type: { type: string }
        expected_yield_kg: { type: number }
        harvest_date: { type: string, format: date }

    PriceInput:
      type: object
      properties:
        expected_yield_kg: { type: number }
        market_trend_index: { type: number }

    MenteeInput:
      type: object
      properties:
        location: { type: string }
        produce_type: { type: string }
        experience_years: { type: integer }
